### ISSUE TITLE
Uputstvo za pokretanje

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/pong-in-ruby#1]
Bilo bi lepo ako bi postojalo uputstvo, tj. spisak svih Gem-ova koji su potrebni za pokretanje (mozda cak i neki script za setup nije losa ideja)

**Comment by bozzano101** [comment]
Dodat je install.sh fajl koji pripremiti sve potrebne gemove i dodatke za instalaciju igrice na bilo kom racunaru.
